LabDS Project/LabDS/LabDS/Controllers/AnalysisCategoryController.cs
using LabDS.App_Start;
using LabDS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabDS.Controllers
{
    public class AnalysisCategoryController : Controller
    {
        public ActionResult List()
        {
            var categories = AnalysisCategory.ListCategories();
            return View(categories);
        }
        public ActionResult Details(int id)
        {
            var category = AnalysisCategory.GetById(id);
            return View(category);
        }

        [HttpGet]
        public ActionResult Insert()
        {
            if (Utils.IsAdmin(Session))
            {
                return View(new AnalysisCategory());
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult Insert(AnalysisCategory model)
        {
            try
            {
                if (Utils.IsAdmin(Session))
                {
                    var dbCategory = AnalysisCategory.GetByName(model.Name);
                    if (dbCategory != null)
                    {
                        ModelState.AddModelError("Name", "Ekziston  nje tjeter kategori me kete emer.");
                        return View(model);
                    }
                    else
                    {
                        if (AnalysisCategory.Insert(model))
                        {
                            return RedirectToAction("List");
                        }
                        else
                        {
                            ModelState.AddModelError("Name", "Nuk u shtua dot!");
                            return View(model);
                        }
                    }
                   
                }
                else
                    return RedirectToAction("Login", "Person");
            }
            catch
            {
                return RedirectToAction("List");
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = AnalysisCategory.GetById(id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(int id, AnalysisCategory category)
        {
            try
            {
                if (Utils.IsAdmin(Session))
                {
                    if (AnalysisCategory.Edit(category))
                        return RedirectToAction("List");
                    else
                        return View(category);
                }
                else
                    return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View(category);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var category = AnalysisCategory.GetById(id);
            return View(category);
        }

        
        [HttpPost]
        public ActionResult Delete(int id, AnalysisCategory category)
        {
            try
            {
                if (Utils.IsAdmin(Session))
                {
                    if (AnalysisCategory.Delete(category))
                    {
                        return RedirectToAction("List");
                    }
                    else return View(category);

                }
                else
                    return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View();
            }
        }
    }
}

LabDS Project/LabDS/LabDS/Controllers/UserController.cs
using LabDS.App_Start;
using LabDS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabDS.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Profile()
        {
            var username = Session["username"].ToString();
            var person = Person.GetByUsername(username);
            return View(person);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Utils.IsUser(Session))
            {
                var person = Person.GetById(id);
                return View(person);
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult Edit(int id, Person model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    if (Person.Edit(model))
                    {
                        return RedirectToAction("Profile");
                    }
                    else
                        return View(model);
                }
                return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: User
        public ActionResult ListPacients()
        {
            var pacients = Pacient.ListPacients();
            return View(pacients);
        }

        [HttpGet]
        public ActionResult AddPacient()
        {
            if (Utils.IsUser(Session))
            {
                return View(new Pacient());
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult AddPacient(Pacient pacient)
        {
            try
            {
                var dbPacient = Pacient.GetByFullName(pacient.Name, pacient.Surname);
                if (dbPacient != null)
                {
                    ModelState.AddModelError("Name", "Pacienti eshte i regjistruar.");
                    return View(pacient);
                }
                if (Pacient.AddPacient(pacient))
                {
                    return RedirectToAction("Insert");
                }
                   
                else
                {
                    ModelState.AddModelError("Name", "Regjistrimi nuk u krye dot.");
                    return View(pacient);
                }
            }
            catch
            {
                ModelState.AddModelError("Name", "Regjistrimi nuk u krye dot.");
                return View(pacient);
            }
        }

        [HttpGet]
        public ActionResult EditPacient(int id)
        {
            if (Utils.IsUser(Session))
            {
                var pacient = Pacient.GetById(id);
                return View(pacient);
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult EditPacient(int id, Pacient model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    if (Pacient.EditPacient(model))
                    {
                        return RedirectToAction("ListPacients");
                    }
                    else
                        return View(model);
                }
                return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult DeletePacient(int id)
        {
            if (Utils.IsUser(Session))
            {
                var pacient = Pacient.GetById(id);
                return View(pacient);
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult DeletePacient(int id, Pacient model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    if (Pacient.DeletePacient(model))
                    {
                        return RedirectToAction("ListPacients");
                    }
                    else
                        return View(model);
                }
                return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View(model);
            }
        }
        public ActionResult ListAnalyzes(int id)
        {
            if (Utils.IsUser(Session))
            {
                var analyzes = PacientAnalysis.ListAnalyzes(id);
                return View(analyzes);
            }
            else
                return RedirectToAction("Login", "Person");
        }
        [HttpGet]
        public ActionResult Insert()
        {
            var analyzes = Analysis.ListAnalyzes();
            ViewData["Analyzes"] = analyzes;
            return View(new PacientAnalysis());
        }

        [HttpPost]
        public ActionResult Insert(PacientAnalysis model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    var analysis = Analysis.GetById(model.AnalysisId);
                    var pacient = Pacient.GetLast();
                    model.PacientId = pacient.Id;
                    model.Name = analysis.Name;
                    model.Price = analysis.Price;
                    model.CategoryId = analysis.CategoryId;
                    PacientAnalysis.Insert(model);
                    var lastAnalysis = PacientAnalysis.GetLast();
                    PacientAnalysisParameter.AddParameter(lastAnalysis);
                    return RedirectToAction("ListPacients");
                }
                else
                    return RedirectToAction("Login", "Person");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult AddAnalysis(int id)
        {
            var analyzes = Analysis.ListAnalyzes();
            ViewData["Analyzes"] = analyzes;
            return View(new PacientAnalysis()
            {
                PacientId =id,
            });
        }

        [HttpPost]
        public ActionResult AddAnalysis(int id, PacientAnalysis model)
        {
            //try
            //{
                if (Utils.IsUser(Session))
                {
                    var analysis = Analysis.GetById(model.AnalysisId);
                    var pacient = Pacient.GetLast();
                    model.PacientId = id;
                    model.Name = analysis.Name;
                    model.Price = analysis.Price;
                    model.CategoryId = analysis.CategoryId;
                    PacientAnalysis.Insert(model);
                    var lastAnalysis = PacientAnalysis.GetLast();
                    PacientAnalysisParameter.AddParameter(lastAnalysis);
                    return RedirectToAction("ListPacients");
                }
                else
                    return RedirectToAction("Login", "Person");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        [HttpGet]
        public ActionResult EditAnalysis(int id)
        {
            if (Utils.IsUser(Session))
            {
                var analysis = PacientAnalysis.GetById(id);
                return View(analysis);
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult EditAnalysis(int id, PacientAnalysis model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    var analysis = PacientAnalysis.GetById(id);
                    model.Id = id;
                    model.AnalysisId = analysis.AnalysisId;
                    model.PacientId = analysis.PacientId;
                    model.CategoryId = analysis.CategoryId;
                    model.Name = analysis.Name;
                    model.CreatedOn = analysis.CreatedOn;

                    if (PacientAnalysis.EditAnalysis(model))
                    {
                        return RedirectToAction("ListAnalyzes");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Modifikimi nuk u krye dot!");
                        return View(model);
                    }                        
                }
                return RedirectToAction("Login", "Person");
            }
            catch
            {
                ModelState.AddModelError("", "Modifikimi nuk u krye dot!");
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult DeleteAnalysis(int id)
        {
            if (Utils.IsUser(Session))
            {
                var analysis = PacientAnalysis.GetById(id);
                return View(analysis);
            }
            else
                return RedirectToAction("Login", "Person");
        }

        [HttpPost]
        public ActionResult DeleteAnalysis(int id, PacientAnalysis model)
        {
            try
            {
                if (Utils.IsUser(Session))
                {
                    int listId = model.PacientId;
                    if (PacientAnalysis.DeleteAnalysis(model))
                    {
                        return RedirectToAction("ListPacients");
                    }
                    else 
                    {
                        ModelState.AddModelError("", "Fshirja nu u krye dot!");
                        return View(model);
                    }
                        
                }
                return RedirectToAction("Login", "Person");
            }
            catch
            {

LabDS Project/LabDS/LabDS/Views/Shared/Plain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LabDS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LabDS Project/LabDS/LabDS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LabDS", "Journal", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["role"].ToString() == "Admin")
                    {
                        <li>@Html.ActionLink("Analysis", "List", "Analysis")</li>
                        <li>@Html.ActionLink("Analysis Category", "List", "AnalysisCategory")</li>
                        <li>@Html.ActionLink("Users", "ListUsers", "Admin")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Pacientet", "ListPacients", "User")</li>
                    }
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["Username"] != null)
                    {
                        <li>
                            @if (Session["role"].ToString() == "Admin")
                            {

                                @Html.ActionLink("Profile", "Profile", "Admin");
                            }
                            else
                            {
                                @Html.ActionLink("Profile", "Profile", "Admin");
                            }
                        </li>
                        <li class=" right">@Html.ActionLink("Logout", "Logout", "Person")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Person")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>